# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_social_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkitemcache',
            name='rss_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='RSS URL'),
        ),
    ]
